### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: FixationNet_150_User1/clusterCenters.npy'

### ISSUE THREAD

**Issue by brankoVanjorek** [CraneHzm/FixationNet#1]
Hi,

I'm trying to run your model, but I'm getting a "FileNotFoundError".

I've followed your steps by downloading the dataset from the website and also downloading the code. I've then run the 'run_FixationNet.sh' file in the script folder of the code. 

The model starts running, but eventually I get the following error:

        ==> Creating the model...
        gazeSeqSize: 80
        headSeqSize: 80
        taskObjectSeqSize: 480
        saliencySize: 1152
        .
        .
        .
        FileNotFoundError: [Errno 2] No such file or directory: '/data2/hzmData/Dataset/dataset/FixationNet_150_User1/clusterCenters.npy'

I've tried placing the dataset file in the same directory as the scripts folder, and also various other locations, but I still get the same error. I've also created a directory with the same pathname to see if the error persisted, and it does.

It seems I just need to place the dataset file in the proper directory, but I'm not sure were to place it. 

Any suggestions on how I could fix this issue?

Any help would be most appreciated.

**Comment by CraneHzm** [comment]
Hello, thanks for your interest. It seems that you have not set the right directory. The training data for this model is saved as zip files at "dataset/FixationNet_150_CrossScene/" and "dataset/FixationNet_150_CrossUser/". You can unzip the zip files and can find everything you need for training your model.

**Comment by brankoVanjorek** [comment]
Hi, thank you very much for your response! I just realised that a number of the files in the dataset zip file were not downloading properly.

For example, in the in the dataset/FixationNet_150_CrossUser/ folder, there were error files such as "FixationNet_150_User1.zip_Error.txt", which contained the following message:

        This file cannot be downloaded. 
        
        ExceptionType: AccessExpiredMeTAException. 
        
        CorrelationId: e13e4e79-0805-48d3-8c76-8dba41575c01, 
        
        UTC DateTime: 09/20/2022 06:01:33

I'm going to try and re-download the files using another web browser and in smaller batches as see if that helps.
